### ISSUE TITLE
Dumping the jobs to a json does not dump the arguments

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#109]
**Describe the bug** / enhancement
Using Django-smuggler, etc, when downloading the data it does not export the arguments. It would be very helpful to have at least some metadata exported that if imported would regenerate the job the way it's supposed to be.

**To Reproduce**
1. Go to Dump data (django-smuggler)
<img width="353" alt="image" src="https://user-images.githubusercontent.com/96071233/227055911-c131eca0-e9e7-4506-b5eb-334279f867e6.png">

**Expected behavior**
a downloaded json that upon importing it back it would also import the parameters

**Comment by cunla** [comment]
I am not sure what is the ask - fix a bug when using another package (which is archived? :) )
