### ISSUE TITLE
Django 4.0 warnings

### ISSUE THREAD

**Issue by MrCocoDev** [cunla/django-rqscheduler#11]
**Describe the bug**
In Django 4.0 apps do not need to declare a default_app_config in the __init__.py file.

**To Reproduce**
1. Add `scheduler` to your `INSTALLED_APPS`

**Expected behavior**
No warnings when the project runs

**Comment by MrCocoDev** [comment]
It's a really easy fix but this project doesn't allow PRs

**Comment by cunla** [comment]
> It's a really easy fix but this project doesn't allow PRs

Hi, apologies, I didn't realize the repo does not allow PRs, can you try now?
