### ISSUE TITLE
Work-horse terminated unexpectedly; waitpid returned 139 (signal 11);  <-- scheduler.tools.run_job

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#112]
**Describe the bug**
Once or twice per day, a job that runs every minute fails like this:
Work-horse terminated unexpectedly; waitpid returned 139 (signal 11); 
(Upon further investigation, signal 11 is a SIGSEGV Error (Address boundary error)).

 scheduler.tools.run_job does for me: only enqueues the real job.

**Desktop (please complete the following information):**
 - OS: alpine-3.17
 - python 3.11
 - django 4.1.7
 - django-rq 2.7.0
 - django-rq-scheduler 2023.3.2

**Additional context**
I just want to see if this happens to anyone, and what are the possible steps to isolate it and fix it.

Thanks!

**Comment by cunla** [comment]
did you encounter it again?

**Comment by gabriels1234** [comment]
@cunla Yes, apr-15 and apr-17 (and probably others that are self-cleaned). It happens with repeatable jobs. Perhaps you can put a dummy job to run every minute. I'm doing it and will update you in a few days.

**Comment by cunla** [comment]
Happens with the latest beta versions?

**Comment by gabriels1234** [comment]
@cunla no, it's a previous .3 version.

I will be testing 2023.5 (rc1). and post an update here asap.

Regarding .5 rc-1 I hope it's backwards compatible with django-rq, also a "drop-in" replacement (e.g it will coexist with django-rq and then easily have the same syntax so one can eventually opt for this implementation). Note that it's pretty common to use django-rq "get_queue()" and perhaps this could have that too. Last but not least, it should be an easy rollback if one is not sure enough about the stability or free-from-errors (especially in the beginning).

In any case, any project upgrading to 2023.5+ would do it in careful steps, because these things need to be "time-tested" and that requires time.

**Comment by cunla** [comment]
You mentioned several things:
1. Before upgrading, use the export/import mgmt commands (see documentation) => This ensures you can rollback if needed.
2. It can coexist with django-rq, however, make sure to go through the installation process to get the new admin views.
3. this package has its own `get_queue`, with better performance.
4. I am intentionally releasing multiple beta versions. There are still bugs (just today found 2), but it is mostly cosmetics. 

I was not able to replicate the error you encountered. I suspect I know what caused it and I fixed it - but without more details, I can't know for sure.

**Comment by cunla** [comment]
Verdict? does it happen on v2023.5.0? I have been using it for about a week now and it does not happen.

**Comment by cunla** [comment]
@gabriels1234 ?

**Comment by cunla** [comment]
I am closing this. Please reopen if problem persists
