### ISSUE TITLE
The max_length of queue name is too short

### ISSUE THREAD

**Issue by gavaig** [cunla/django-rqscheduler#136]
**Describe the bug**

**To Reproduce**
1. Go to settings and add the queue with a name more than 16 characters long.
2. Try to run the project
3. See error:
```SystemCheckError: System check identified some issues:

ERRORS:
scheduler.CronJob.queue: (fields.E009) 'max_length' is too small to fit the longest value in 'choices' (33 characters).
scheduler.RepeatableJob.queue: (fields.E009) 'max_length' is too small to fit the longest value in 'choices' (33 characters).
scheduler.ScheduledJob.queue: (fields.E009) 'max_length' is too small to fit the longest value in 'choices' (33 characters).
```

**Expected behavior**
Need to extend the queue name size up to 255 characters (default value) and project have to run successfully.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - python version 3.10.11
 - django version 4.2.1
 - django-rq-scheduler version 2023.5.0

**Additional context**
Actually I just need to add the previously created long queue names which cannot be changed.
The problem is in BaseJob class [here](https://github.com/dsoftwareinc/django-rq-scheduler/blob/master/scheduler/models/scheduled_job.py#L54)

Thank you,
Ihor

**Comment by cunla** [comment]
Hi, ok, I did not realize such long names are needed. Will fix in the next version unless you want to create a PR?

**Comment by gavaig** [comment]
Yeah, I can create the PR

Thank you

**Comment by gavaig** [comment]
@cunla cannot push my branch to remote. Can you add the permissions, please?

**Comment by cunla** [comment]
Hi, you should be able to fork the repo and create a PR
