### ISSUE TITLE
Package incompatible with >=Django 3.2

### ISSUE THREAD

**Issue by Cybernisk** [cunla/django-rqscheduler#17]
**Describe the bug**
According to the changes in PIP (see [changes-to-the-pip-dependency-resolver](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020)) now `django-rq-scheduler` shows as incompatible during install with >=Django 3.2

**To Reproduce**
1. Create requirement file with, for example, `django==3.2.1 django-rq-scheduler==2022.5`
2. `pip install -r requirements.txt`
3. Error message:

> The conflict is caused by:
    The user requested django==3.2.1
    django-rq-scheduler 2022.5 depends on django>=4.0

**Expected behavior**
Installed successfully as package supports Django>=3.2

**Desktop:**
 - OS: any
- pip: >=21.0

**Comment by cunla** [comment]
Fixed in v2022.5.1
