### ISSUE TITLE
Add option to not depend on rq-scheduler

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#56]
**Is your feature request related to a problem? Please describe.**

RQ (already from version 1.2.0, now on 1.11.1) provides support for a worker (or many workers) to also behave as schedulers (1 active at a time). The main motivation is cost, having a scheduler for each project means an extra container/pod

Django-RQ already supports this, with `get_scheduler()` being either a Scheduler (rq-scheduler) or fallback as a Queue

**Describe the solution you'd like**
I'd like to contribute on how to offer that kind of fallback to django-rq-scheduler. 

**Describe alternatives you've considered**
I believe the ability to display and manage jobs is (or should allow to be)  separate from the task of running the scheduler itself.

**Comment by cunla** [comment]
This is not straight-forward. 

`get_scheduler` on [django_rq](https://github.com/rq/django-rq/blob/master/django_rq/queues.py#L305-L307) is not implemented when rq-scheduler is not imported, and it means shifting the entire logic of rq-scheduler to this package (including `.cron()`, `__contains__()`, ...).

**Comment by cunla** [comment]
I managed to remove the dependency on rq_scheduler in v2022.1.0-beta
