### ISSUE TITLE
at_front via kwargs not working

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#65]
(cross-posted also to django-rq):

<img width="324" alt="image" src="https://user-images.githubusercontent.com/96071233/208116561-76f2f903-f191-4c9b-9724-a6c962962035.png">

I have this setting in the job, and still cannot get this job to be processed first, namely to be placed at the front of the queue.

I'm using django-rq, with django-rq-scheduler. In "Cron jobs" page I set the job's details as this:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/96071233/208116834-f89f6ffb-9e4b-455f-8b05-cc858a2bbb50.png">

And as per the first image, it seems to have been picked up by django-rq.

Any ideas/help would be appreciated.

**Comment by gabriels1234** [comment]
It seems that it works, but it's a kwarg sent to the job instead, not to the enqueue method.

**Comment by cunla** [comment]
Yeah, I have an issue open to calculate the value of kwargs in run time. #22

**Comment by gabriels1234** [comment]
Update: I've checked both rq, django-rq, and rq-scheduler and they simply ignore the at_front argument.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/96071233/208137394-786cea50-3c94-4d5a-aa06-575af5854ba6.png">


However, there could be a way to achieve almost the same within this project.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/96071233/208136339-44739d72-1a83-472f-9e98-7bf380d46bf7.png">

Perhaps you could add to the cron section an "offset" that could be set to a negative value:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/96071233/208136579-411648cd-2b7c-455c-9a56-cbc0f6a2418c.png">


What do you think?

**Comment by cunla** [comment]
I don't think they ignore it. It simply passed in the `**kwargs`

**Comment by gabriels1234** [comment]
look for yourself:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/96071233/208152773-1228150e-3d14-4d11-b62f-00f9fdf16e4f.png">

**Comment by gabriels1234** [comment]
I think adding the offset, so when it's enqueued_at the offset is applied (and effectively "enqueues_at" one hour less than `self.schedule_time_utc() ) will put it as at the front as possible. What do you think?

**Comment by cunla** [comment]
Ok, after looking deeper into the issue:
You can't control the order of jobs using job parameters. You can have multiple queues for different priorities.

**Comment by gabriels1234** [comment]
Hi @cunla Thank you so much!!!
I had a PR ready to add something similar to this.
However, I also saw that perhaps the work needs to be done in rq and rq-scheduler (and I'm opening a PR on both projects after they suggested me to do so).
In the case of this project, perhaps it could have been handled by adding the at_front on the kwargs (which then is popped by rq /rq-scheduler).
Moreover, I'm super excited, How do I get access to release 2023.1?

Thanks so much!

**Comment by cunla** [comment]
Hi, I released it as [beta for now](https://pypi.org/manage/project/django-rq-scheduler/release/2023.1.0b2/) - It is a major change with not using rq_scheduler. I want to try multiple scenarios before officially releasing it.

**Comment by gabriels1234** [comment]
if you asked, these are the final minimal changes to add at_front to django-rq-scheduler (and also add a separate action).
(it would rely on rq, and rq scheduler to have some minimal changes). What do you think?

<img width="828" alt="image" src="https://user-images.githubusercontent.com/96071233/208457215-e47ead3a-1adf-43a2-8462-1fbd7f09d19b.png">

**Comment by gabriels1234** [comment]
@cunla How did you manage to have the "schedule at front" feature without the necessary change in rq?
I have this [PR](https://github.com/rq/rq/pull/1743) that would make the change serious in rq so It can be finally used in production.

**Comment by cunla** [comment]
See [this commit](https://github.com/dsoftwareinc/django-rq-scheduler/commit/08324ad92b5c79de1500cacd4f26f81588792392)
