### ISSUE TITLE
Run Now not running when job is already scheduled

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#80]
**Describe the bug**
"Run Now" has no effect for jobs that are already scheduled (or cron'ed with the new cron)

One option would be to replace in admin.py, line 113: enqueue_at( ... 
with enqueue(... (remove the first parameter)

Thanks!!

**Comment by gabriels1234** [comment]
@cunla question: how would you like this issue to be addressed. As of now, the "run now" action has no effect on enabled cronjobs/repeated jobs.

One way to go about is to remove that scheduled entry and schedule now.

Let me know if I can be of help here. The PR might be small, but I don't want to go in a direction you don't like to begin with.

Thanks!

**Comment by cunla** [comment]
I haven't thought about it.
If it is urgent for you, you can extend the given admin interface - I want to address other issues before.

**Comment by gabriels1234** [comment]
@cunla I will work on this because end-users are used to do "Run Now" and expect it to run now. So the fix will just go and find the job in the scheduled registry and if there's a scheduled job with same callable, will remove it and then enqueue_at(now()...) (to account for any change). it might not be perfect for every case, but keeping it like it's now it's misleading (the more so because the previous behavior was different).
Let me know, looking forward to it!

**Comment by cunla** [comment]
Do you know how to trigger a dialog box form in django-admin?

I would want to have a list of the selected jobs to "Run now" and tell the user the jobs will be unscheduled for their next run 

This is true for `ScheduledJob` and `RepeatableJob` but not for `CronJob`.

**Comment by gabriels1234** [comment]
I can give it a shot.
However, if we each are worried about a different set of jobs (I'm mostly worried about enabling "Run Now" for CronJobs), I can focus on fixing that first (which would be to "enqueue() " the job (vs enqueue_at)) and it's much straightforward.

Tell me if I understood you correctly.
Also, perhaps We can change the wording to "Enqueue Now" and that way everyone would be aware of what's going on.
(I thought of the workaround because you were worried about sensitive jobs being ran more than expected. But if you are not worried of CronJobs, then I can start with my easy feature and see how it goes. I'd do whatever you prefer).

**Comment by gabriels1234** [comment]
@cunla I will start with the easiest change, then you tell me.
That is:
- Renaming "Run Now" to "Enqueue Now" (queue.enqueue_at(now())) and make a "Run Now" that calls queue.enqueue()
