### ISSUE TITLE
Stale scheduled jobs (whose responsibility, what to do about it?)

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#81]
Hi!

I'm testing manually the resiliency of the new cron (2023.1+).

I came across a "(cron)scheduled job" that is scheduled in the past. Other jobs are picked up from that registry and queued, but this job doesn't.

Question 1: does the job exist? (or is it an artifact)
Question 2: is it RQ's responsibility? (and for some reason it's not picking it up?)
Question 3: can we do something about it? (e.g enqueue it if we see that it's X time old, and the queue is empty and there's 0 active jobs in that queue? (all things we can know about with certainty))

Thanks!

**Comment by cunla** [comment]
Fixed, added `Job scheduling jobs`
