### ISSUE TITLE
Add to admin visibility whether there is a scheduler running

### ISSUE THREAD

**Issue by cunla** [cunla/django-rqscheduler#83]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to know whether there is a worker with a scheduler.

**Describe the solution you'd like**
Add a check whether there is a worker with a scheduler and make it visible in the admin view.

**Comment by gabriels1234** [comment]
@cunla I was checking and apparently, that is possible, by querying directly to redis. Would you entertain me going this path?
Also, the best place for this check would be django-rq, where a column cold be for each queue to say if a scheduler (/worker-scheduler, it's the same) is attached to each queue.

**Comment by cunla** [comment]
Since this package is a wrapper on top of `django-rq` (which is on top of `rq`) - I recommend not going this path on `django-rq-scheduler`. If they choose to change implementation it will break.
But generally speaking, in `rq` you can see redis commands.
